# application.yml - Main configuration file
spring:
  application:
    name: pearlcard-metro-api
  profiles:
    active: dev

server:
  port: 8080

# Station to Zone Mappings
stations:
  station-to-zone-map:
    # Zone 1 - Central Business District
    PEARL_CENTRAL: 1
    DOWNTOWN: 1
    CITY_HALL: 1
    FINANCIAL: 1
    PEARL_PLAZA: 1
    CENTRAL_PARK: 1
    BUSINESS_DISTRICT: 1
    
    # Zone 2 - Suburban Areas
    NORTH_PEARL: 2
    EAST_PEARL: 2
    WEST_PEARL: 2
    SOUTH_PEARL: 2
    MIDTOWN: 2
    UNIVERSITY: 2
    HOSPITAL: 2
    SHOPPING_CENTER: 2
    RESIDENTIAL_NORTH: 2
    RESIDENTIAL_SOUTH: 2
    
    # Zone 3 - Outer Areas
    AIRPORT: 3
    INDUSTRIAL: 3
    SUBURBAN: 3
    BEACH: 3
    MOUNTAINS: 3
    TECH_PARK: 3
    RESIDENTIAL_OUTER: 3
    CARGO_TERMINAL: 3
    SPORTS_COMPLEX: 3

# Fare Structure (Zone combinations to fare in cents)
fares:
  zone-to-fare-map:
    # Zone 1 combinations
    "1-1": 40
    "1-2": 55
    "1-3": 65
    
    # Zone 2 combinations  
    "2-1": 55
    "2-2": 35
    "2-3": 45
    
    # Zone 3 combinations
    "3-1": 65
    "3-2": 45
    "3-3": 30
